// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/relay_api.dart';
import 'api/simple.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthResultResponse dco_decode_auth_result_response(dynamic raw);

  @protected
  AuthStatusResponse dco_decode_auth_status_response(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ConflictResponse dco_decode_conflict_response(dynamic raw);

  @protected
  EnrichResult dco_decode_enrich_result(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FeedHighlightResponse dco_decode_feed_highlight_response(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConflictResponse> dco_decode_list_conflict_response(dynamic raw);

  @protected
  List<FeedHighlightResponse> dco_decode_list_feed_highlight_response(
    dynamic raw,
  );

  @protected
  List<ListedHighlightResponse> dco_decode_list_listed_highlight_response(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchResultResponse> dco_decode_list_search_result_response(
    dynamic raw,
  );

  @protected
  List<StreamInfoResponse> dco_decode_list_stream_info_response(dynamic raw);

  @protected
  ListedHighlightResponse dco_decode_listed_highlight_response(dynamic raw);

  @protected
  ModelStatusResponse dco_decode_model_status_response(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SearchResultResponse dco_decode_search_result_response(dynamic raw);

  @protected
  SourceMetaResponse dco_decode_source_meta_response(dynamic raw);

  @protected
  StreamInfoResponse dco_decode_stream_info_response(dynamic raw);

  @protected
  SyncReportResponse dco_decode_sync_report_response(dynamic raw);

  @protected
  SyncStatusResponse dco_decode_sync_status_response(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthResultResponse sse_decode_auth_result_response(
    SseDeserializer deserializer,
  );

  @protected
  AuthStatusResponse sse_decode_auth_status_response(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ConflictResponse sse_decode_conflict_response(SseDeserializer deserializer);

  @protected
  EnrichResult sse_decode_enrich_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FeedHighlightResponse sse_decode_feed_highlight_response(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConflictResponse> sse_decode_list_conflict_response(
    SseDeserializer deserializer,
  );

  @protected
  List<FeedHighlightResponse> sse_decode_list_feed_highlight_response(
    SseDeserializer deserializer,
  );

  @protected
  List<ListedHighlightResponse> sse_decode_list_listed_highlight_response(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchResultResponse> sse_decode_list_search_result_response(
    SseDeserializer deserializer,
  );

  @protected
  List<StreamInfoResponse> sse_decode_list_stream_info_response(
    SseDeserializer deserializer,
  );

  @protected
  ListedHighlightResponse sse_decode_listed_highlight_response(
    SseDeserializer deserializer,
  );

  @protected
  ModelStatusResponse sse_decode_model_status_response(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SearchResultResponse sse_decode_search_result_response(
    SseDeserializer deserializer,
  );

  @protected
  SourceMetaResponse sse_decode_source_meta_response(
    SseDeserializer deserializer,
  );

  @protected
  StreamInfoResponse sse_decode_stream_info_response(
    SseDeserializer deserializer,
  );

  @protected
  SyncReportResponse sse_decode_sync_report_response(
    SseDeserializer deserializer,
  );

  @protected
  SyncStatusResponse sse_decode_sync_status_response(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_result_response(
    AuthResultResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_auth_status_response(
    AuthStatusResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_response(
    ConflictResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_enrich_result(EnrichResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_feed_highlight_response(
    FeedHighlightResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conflict_response(
    List<ConflictResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_feed_highlight_response(
    List<FeedHighlightResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_listed_highlight_response(
    List<ListedHighlightResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result_response(
    List<SearchResultResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stream_info_response(
    List<StreamInfoResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_listed_highlight_response(
    ListedHighlightResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_status_response(
    ModelStatusResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_search_result_response(
    SearchResultResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_meta_response(
    SourceMetaResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stream_info_response(
    StreamInfoResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_report_response(
    SyncReportResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_status_response(
    SyncStatusResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
