// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/relay_api.dart';
import 'api/simple.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -694537443;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'relay_mobile_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiRelayApiAddHighlightToStream({
    required String streamId,
    required String highlightId,
  });

  void crateApiRelayApiClearLocalData();

  AuthResultResponse crateApiRelayApiCreateAccount({
    required String email,
    required String password,
  });

  String crateApiRelayApiCreateStream({
    required String title,
    required String description,
  });

  void crateApiRelayApiDeleteHighlight({required String id});

  EnrichResult crateApiRelayApiEnrichAndStore({required String text});

  String crateApiRelayApiExportLocalData();

  SourceMetaResponse crateApiRelayApiExtractSourceMetadata({
    required String text,
  });

  AuthStatusResponse crateApiRelayApiGetAuthStatus();

  bool crateApiRelayApiGetAutoCaptureEnabled();

  List<ConflictResponse> crateApiRelayApiGetConflicts();

  ModelStatusResponse crateApiRelayApiGetModelStatus();

  StreamInfoResponse crateApiRelayApiGetStream({required String streamId});

  List<FeedHighlightResponse> crateApiRelayApiGetSubscriberFeed({
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  SyncStatusResponse crateApiRelayApiGetSyncStatus();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  void crateApiRelayApiInitCore({required String dataDir});

  List<StreamInfoResponse> crateApiRelayApiListMyStreams();

  List<ListedHighlightResponse> crateApiRelayApiListStoredHighlights({
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  void crateApiRelayApiLogEvent({
    required String eventType,
    String? streamId,
    String? channel,
  });

  AuthResultResponse crateApiRelayApiLogIn({
    required String email,
    required String password,
  });

  void crateApiRelayApiLogOut();

  void crateApiRelayApiRegisterDeviceToken({
    required String token,
    required String platform,
  });

  void crateApiRelayApiResolveConflict({
    required String id,
    required String resolution,
  });

  List<SearchResultResponse> crateApiRelayApiSearchHighlights({
    required String query,
    required PlatformInt64 limit,
  });

  void crateApiRelayApiSetAutoCaptureEnabled({required bool enabled});

  String crateApiRelayApiStoreHighlight({
    required String text,
    required String summary,
    required List<String> tags,
    String? sourceUrl,
    String? sourceTitle,
    String? sourceAuthor,
  });

  void crateApiRelayApiSubscribeToStream({required String streamId});

  SyncReportResponse crateApiRelayApiSyncNow();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiRelayApiAddHighlightToStream({
    required String streamId,
    required String highlightId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(streamId, serializer);
          sse_encode_String(highlightId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiAddHighlightToStreamConstMeta,
        argValues: [streamId, highlightId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiAddHighlightToStreamConstMeta =>
      const TaskConstMeta(
        debugName: "add_highlight_to_stream",
        argNames: ["streamId", "highlightId"],
      );

  @override
  void crateApiRelayApiClearLocalData() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiClearLocalDataConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiClearLocalDataConstMeta =>
      const TaskConstMeta(debugName: "clear_local_data", argNames: []);

  @override
  AuthResultResponse crateApiRelayApiCreateAccount({
    required String email,
    required String password,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(email, serializer);
          sse_encode_String(password, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_result_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiCreateAccountConstMeta,
        argValues: [email, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiCreateAccountConstMeta =>
      const TaskConstMeta(
        debugName: "create_account",
        argNames: ["email", "password"],
      );

  @override
  String crateApiRelayApiCreateStream({
    required String title,
    required String description,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(description, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiCreateStreamConstMeta,
        argValues: [title, description],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiCreateStreamConstMeta =>
      const TaskConstMeta(
        debugName: "create_stream",
        argNames: ["title", "description"],
      );

  @override
  void crateApiRelayApiDeleteHighlight({required String id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiDeleteHighlightConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiDeleteHighlightConstMeta =>
      const TaskConstMeta(debugName: "delete_highlight", argNames: ["id"]);

  @override
  EnrichResult crateApiRelayApiEnrichAndStore({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_enrich_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiEnrichAndStoreConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiEnrichAndStoreConstMeta =>
      const TaskConstMeta(debugName: "enrich_and_store", argNames: ["text"]);

  @override
  String crateApiRelayApiExportLocalData() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiExportLocalDataConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiExportLocalDataConstMeta =>
      const TaskConstMeta(debugName: "export_local_data", argNames: []);

  @override
  SourceMetaResponse crateApiRelayApiExtractSourceMetadata({
    required String text,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_source_meta_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiExtractSourceMetadataConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiExtractSourceMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "extract_source_metadata",
        argNames: ["text"],
      );

  @override
  AuthStatusResponse crateApiRelayApiGetAuthStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_status_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiGetAuthStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiGetAuthStatusConstMeta =>
      const TaskConstMeta(debugName: "get_auth_status", argNames: []);

  @override
  bool crateApiRelayApiGetAutoCaptureEnabled() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiGetAutoCaptureEnabledConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiGetAutoCaptureEnabledConstMeta =>
      const TaskConstMeta(debugName: "get_auto_capture_enabled", argNames: []);

  @override
  List<ConflictResponse> crateApiRelayApiGetConflicts() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conflict_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiGetConflictsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiGetConflictsConstMeta =>
      const TaskConstMeta(debugName: "get_conflicts", argNames: []);

  @override
  ModelStatusResponse crateApiRelayApiGetModelStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_model_status_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiGetModelStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiGetModelStatusConstMeta =>
      const TaskConstMeta(debugName: "get_model_status", argNames: []);

  @override
  StreamInfoResponse crateApiRelayApiGetStream({required String streamId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(streamId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stream_info_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiGetStreamConstMeta,
        argValues: [streamId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiGetStreamConstMeta =>
      const TaskConstMeta(debugName: "get_stream", argNames: ["streamId"]);

  @override
  List<FeedHighlightResponse> crateApiRelayApiGetSubscriberFeed({
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(limit, serializer);
          sse_encode_i_64(offset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_feed_highlight_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiGetSubscriberFeedConstMeta,
        argValues: [limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiGetSubscriberFeedConstMeta =>
      const TaskConstMeta(
        debugName: "get_subscriber_feed",
        argNames: ["limit", "offset"],
      );

  @override
  SyncStatusResponse crateApiRelayApiGetSyncStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_status_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiGetSyncStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiGetSyncStatusConstMeta =>
      const TaskConstMeta(debugName: "get_sync_status", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiRelayApiInitCore({required String dataDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiInitCoreConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiInitCoreConstMeta =>
      const TaskConstMeta(debugName: "init_core", argNames: ["dataDir"]);

  @override
  List<StreamInfoResponse> crateApiRelayApiListMyStreams() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_stream_info_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiListMyStreamsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiListMyStreamsConstMeta =>
      const TaskConstMeta(debugName: "list_my_streams", argNames: []);

  @override
  List<ListedHighlightResponse> crateApiRelayApiListStoredHighlights({
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(limit, serializer);
          sse_encode_i_64(offset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_listed_highlight_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiListStoredHighlightsConstMeta,
        argValues: [limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiListStoredHighlightsConstMeta =>
      const TaskConstMeta(
        debugName: "list_stored_highlights",
        argNames: ["limit", "offset"],
      );

  @override
  void crateApiRelayApiLogEvent({
    required String eventType,
    String? streamId,
    String? channel,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(eventType, serializer);
          sse_encode_opt_String(streamId, serializer);
          sse_encode_opt_String(channel, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiLogEventConstMeta,
        argValues: [eventType, streamId, channel],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiLogEventConstMeta => const TaskConstMeta(
    debugName: "log_event",
    argNames: ["eventType", "streamId", "channel"],
  );

  @override
  AuthResultResponse crateApiRelayApiLogIn({
    required String email,
    required String password,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(email, serializer);
          sse_encode_String(password, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_result_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiLogInConstMeta,
        argValues: [email, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiLogInConstMeta =>
      const TaskConstMeta(debugName: "log_in", argNames: ["email", "password"]);

  @override
  void crateApiRelayApiLogOut() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiLogOutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiLogOutConstMeta =>
      const TaskConstMeta(debugName: "log_out", argNames: []);

  @override
  void crateApiRelayApiRegisterDeviceToken({
    required String token,
    required String platform,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(platform, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiRegisterDeviceTokenConstMeta,
        argValues: [token, platform],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiRegisterDeviceTokenConstMeta =>
      const TaskConstMeta(
        debugName: "register_device_token",
        argNames: ["token", "platform"],
      );

  @override
  void crateApiRelayApiResolveConflict({
    required String id,
    required String resolution,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(resolution, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiResolveConflictConstMeta,
        argValues: [id, resolution],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiResolveConflictConstMeta =>
      const TaskConstMeta(
        debugName: "resolve_conflict",
        argNames: ["id", "resolution"],
      );

  @override
  List<SearchResultResponse> crateApiRelayApiSearchHighlights({
    required String query,
    required PlatformInt64 limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_i_64(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_result_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiSearchHighlightsConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiSearchHighlightsConstMeta =>
      const TaskConstMeta(
        debugName: "search_highlights",
        argNames: ["query", "limit"],
      );

  @override
  void crateApiRelayApiSetAutoCaptureEnabled({required bool enabled}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiSetAutoCaptureEnabledConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiSetAutoCaptureEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_auto_capture_enabled",
        argNames: ["enabled"],
      );

  @override
  String crateApiRelayApiStoreHighlight({
    required String text,
    required String summary,
    required List<String> tags,
    String? sourceUrl,
    String? sourceTitle,
    String? sourceAuthor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_String(summary, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_opt_String(sourceUrl, serializer);
          sse_encode_opt_String(sourceTitle, serializer);
          sse_encode_opt_String(sourceAuthor, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiStoreHighlightConstMeta,
        argValues: [text, summary, tags, sourceUrl, sourceTitle, sourceAuthor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiStoreHighlightConstMeta =>
      const TaskConstMeta(
        debugName: "store_highlight",
        argNames: [
          "text",
          "summary",
          "tags",
          "sourceUrl",
          "sourceTitle",
          "sourceAuthor",
        ],
      );

  @override
  void crateApiRelayApiSubscribeToStream({required String streamId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(streamId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiSubscribeToStreamConstMeta,
        argValues: [streamId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiSubscribeToStreamConstMeta =>
      const TaskConstMeta(
        debugName: "subscribe_to_stream",
        argNames: ["streamId"],
      );

  @override
  SyncReportResponse crateApiRelayApiSyncNow() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_report_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRelayApiSyncNowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRelayApiSyncNowConstMeta =>
      const TaskConstMeta(debugName: "sync_now", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthResultResponse dco_decode_auth_result_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AuthResultResponse(
      token: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
    );
  }

  @protected
  AuthStatusResponse dco_decode_auth_status_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AuthStatusResponse(
      loggedIn: dco_decode_bool(arr[0]),
      email: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConflictResponse dco_decode_conflict_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ConflictResponse(
      id: dco_decode_String(arr[0]),
      recordType: dco_decode_String(arr[1]),
      recordId: dco_decode_String(arr[2]),
    );
  }

  @protected
  EnrichResult dco_decode_enrich_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return EnrichResult(
      id: dco_decode_String(arr[0]),
      summary: dco_decode_String(arr[1]),
      tags: dco_decode_list_String(arr[2]),
      suggestionHighlightId: dco_decode_opt_String(arr[3]),
      suggestionBridgingSentence: dco_decode_opt_String(arr[4]),
      sourceUrl: dco_decode_opt_String(arr[5]),
      sourceTitle: dco_decode_opt_String(arr[6]),
      sourceAuthor: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FeedHighlightResponse dco_decode_feed_highlight_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FeedHighlightResponse(
      id: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
      summary: dco_decode_String(arr[2]),
      tags: dco_decode_list_String(arr[3]),
      streamTitle: dco_decode_String(arr[4]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConflictResponse> dco_decode_list_conflict_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conflict_response).toList();
  }

  @protected
  List<FeedHighlightResponse> dco_decode_list_feed_highlight_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_feed_highlight_response)
        .toList();
  }

  @protected
  List<ListedHighlightResponse> dco_decode_list_listed_highlight_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_listed_highlight_response)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SearchResultResponse> dco_decode_list_search_result_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_search_result_response)
        .toList();
  }

  @protected
  List<StreamInfoResponse> dco_decode_list_stream_info_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stream_info_response).toList();
  }

  @protected
  ListedHighlightResponse dco_decode_listed_highlight_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ListedHighlightResponse(
      id: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
      summary: dco_decode_String(arr[2]),
      tags: dco_decode_list_String(arr[3]),
      createdAt: dco_decode_String(arr[4]),
      sourceUrl: dco_decode_opt_String(arr[5]),
      sourceTitle: dco_decode_opt_String(arr[6]),
      sourceAuthor: dco_decode_opt_String(arr[7]),
      connectionSuggestion: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  ModelStatusResponse dco_decode_model_status_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ModelStatusResponse(
      loaded: dco_decode_bool(arr[0]),
      modelName: dco_decode_String(arr[1]),
      backend: dco_decode_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SearchResultResponse dco_decode_search_result_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SearchResultResponse(
      id: dco_decode_String(arr[0]),
      summary: dco_decode_String(arr[1]),
      tags: dco_decode_list_String(arr[2]),
      text: dco_decode_String(arr[3]),
      score: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  SourceMetaResponse dco_decode_source_meta_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SourceMetaResponse(
      sourceUrl: dco_decode_opt_String(arr[0]),
      sourceTitle: dco_decode_opt_String(arr[1]),
      sourceAuthor: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  StreamInfoResponse dco_decode_stream_info_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StreamInfoResponse(
      id: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      description: dco_decode_String(arr[3]),
    );
  }

  @protected
  SyncReportResponse dco_decode_sync_report_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SyncReportResponse(
      pushed: dco_decode_i_64(arr[0]),
      pulled: dco_decode_i_64(arr[1]),
      conflicts: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  SyncStatusResponse dco_decode_sync_status_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SyncStatusResponse(
      status: dco_decode_String(arr[0]),
      pendingCount: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthResultResponse sse_decode_auth_result_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_token = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    return AuthResultResponse(token: var_token, userId: var_userId);
  }

  @protected
  AuthStatusResponse sse_decode_auth_status_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loggedIn = sse_decode_bool(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    return AuthStatusResponse(loggedIn: var_loggedIn, email: var_email);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConflictResponse sse_decode_conflict_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_recordType = sse_decode_String(deserializer);
    var var_recordId = sse_decode_String(deserializer);
    return ConflictResponse(
      id: var_id,
      recordType: var_recordType,
      recordId: var_recordId,
    );
  }

  @protected
  EnrichResult sse_decode_enrich_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_suggestionHighlightId = sse_decode_opt_String(deserializer);
    var var_suggestionBridgingSentence = sse_decode_opt_String(deserializer);
    var var_sourceUrl = sse_decode_opt_String(deserializer);
    var var_sourceTitle = sse_decode_opt_String(deserializer);
    var var_sourceAuthor = sse_decode_opt_String(deserializer);
    return EnrichResult(
      id: var_id,
      summary: var_summary,
      tags: var_tags,
      suggestionHighlightId: var_suggestionHighlightId,
      suggestionBridgingSentence: var_suggestionBridgingSentence,
      sourceUrl: var_sourceUrl,
      sourceTitle: var_sourceTitle,
      sourceAuthor: var_sourceAuthor,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FeedHighlightResponse sse_decode_feed_highlight_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_streamTitle = sse_decode_String(deserializer);
    return FeedHighlightResponse(
      id: var_id,
      text: var_text,
      summary: var_summary,
      tags: var_tags,
      streamTitle: var_streamTitle,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConflictResponse> sse_decode_list_conflict_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConflictResponse>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conflict_response(deserializer));
    }
    return ans_;
  }

  @protected
  List<FeedHighlightResponse> sse_decode_list_feed_highlight_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FeedHighlightResponse>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_feed_highlight_response(deserializer));
    }
    return ans_;
  }

  @protected
  List<ListedHighlightResponse> sse_decode_list_listed_highlight_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ListedHighlightResponse>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_listed_highlight_response(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SearchResultResponse> sse_decode_list_search_result_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchResultResponse>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_result_response(deserializer));
    }
    return ans_;
  }

  @protected
  List<StreamInfoResponse> sse_decode_list_stream_info_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StreamInfoResponse>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stream_info_response(deserializer));
    }
    return ans_;
  }

  @protected
  ListedHighlightResponse sse_decode_listed_highlight_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_sourceUrl = sse_decode_opt_String(deserializer);
    var var_sourceTitle = sse_decode_opt_String(deserializer);
    var var_sourceAuthor = sse_decode_opt_String(deserializer);
    var var_connectionSuggestion = sse_decode_opt_String(deserializer);
    return ListedHighlightResponse(
      id: var_id,
      text: var_text,
      summary: var_summary,
      tags: var_tags,
      createdAt: var_createdAt,
      sourceUrl: var_sourceUrl,
      sourceTitle: var_sourceTitle,
      sourceAuthor: var_sourceAuthor,
      connectionSuggestion: var_connectionSuggestion,
    );
  }

  @protected
  ModelStatusResponse sse_decode_model_status_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loaded = sse_decode_bool(deserializer);
    var var_modelName = sse_decode_String(deserializer);
    var var_backend = sse_decode_String(deserializer);
    return ModelStatusResponse(
      loaded: var_loaded,
      modelName: var_modelName,
      backend: var_backend,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SearchResultResponse sse_decode_search_result_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return SearchResultResponse(
      id: var_id,
      summary: var_summary,
      tags: var_tags,
      text: var_text,
      score: var_score,
    );
  }

  @protected
  SourceMetaResponse sse_decode_source_meta_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceUrl = sse_decode_opt_String(deserializer);
    var var_sourceTitle = sse_decode_opt_String(deserializer);
    var var_sourceAuthor = sse_decode_opt_String(deserializer);
    return SourceMetaResponse(
      sourceUrl: var_sourceUrl,
      sourceTitle: var_sourceTitle,
      sourceAuthor: var_sourceAuthor,
    );
  }

  @protected
  StreamInfoResponse sse_decode_stream_info_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return StreamInfoResponse(
      id: var_id,
      userId: var_userId,
      title: var_title,
      description: var_description,
    );
  }

  @protected
  SyncReportResponse sse_decode_sync_report_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pushed = sse_decode_i_64(deserializer);
    var var_pulled = sse_decode_i_64(deserializer);
    var var_conflicts = sse_decode_i_64(deserializer);
    return SyncReportResponse(
      pushed: var_pushed,
      pulled: var_pulled,
      conflicts: var_conflicts,
    );
  }

  @protected
  SyncStatusResponse sse_decode_sync_status_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_pendingCount = sse_decode_i_64(deserializer);
    return SyncStatusResponse(
      status: var_status,
      pendingCount: var_pendingCount,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_result_response(
    AuthResultResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.userId, serializer);
  }

  @protected
  void sse_encode_auth_status_response(
    AuthStatusResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.loggedIn, serializer);
    sse_encode_opt_String(self.email, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_conflict_response(
    ConflictResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.recordType, serializer);
    sse_encode_String(self.recordId, serializer);
  }

  @protected
  void sse_encode_enrich_result(EnrichResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.suggestionHighlightId, serializer);
    sse_encode_opt_String(self.suggestionBridgingSentence, serializer);
    sse_encode_opt_String(self.sourceUrl, serializer);
    sse_encode_opt_String(self.sourceTitle, serializer);
    sse_encode_opt_String(self.sourceAuthor, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_feed_highlight_response(
    FeedHighlightResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.streamTitle, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conflict_response(
    List<ConflictResponse> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conflict_response(item, serializer);
    }
  }

  @protected
  void sse_encode_list_feed_highlight_response(
    List<FeedHighlightResponse> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_feed_highlight_response(item, serializer);
    }
  }

  @protected
  void sse_encode_list_listed_highlight_response(
    List<ListedHighlightResponse> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_listed_highlight_response(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_search_result_response(
    List<SearchResultResponse> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_result_response(item, serializer);
    }
  }

  @protected
  void sse_encode_list_stream_info_response(
    List<StreamInfoResponse> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stream_info_response(item, serializer);
    }
  }

  @protected
  void sse_encode_listed_highlight_response(
    ListedHighlightResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_opt_String(self.sourceUrl, serializer);
    sse_encode_opt_String(self.sourceTitle, serializer);
    sse_encode_opt_String(self.sourceAuthor, serializer);
    sse_encode_opt_String(self.connectionSuggestion, serializer);
  }

  @protected
  void sse_encode_model_status_response(
    ModelStatusResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.loaded, serializer);
    sse_encode_String(self.modelName, serializer);
    sse_encode_String(self.backend, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_search_result_response(
    SearchResultResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_source_meta_response(
    SourceMetaResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.sourceUrl, serializer);
    sse_encode_opt_String(self.sourceTitle, serializer);
    sse_encode_opt_String(self.sourceAuthor, serializer);
  }

  @protected
  void sse_encode_stream_info_response(
    StreamInfoResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_sync_report_response(
    SyncReportResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.pushed, serializer);
    sse_encode_i_64(self.pulled, serializer);
    sse_encode_i_64(self.conflicts, serializer);
  }

  @protected
  void sse_encode_sync_status_response(
    SyncStatusResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_i_64(self.pendingCount, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
