// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

void initCore({required String dataDir}) =>
    RustLib.instance.api.crateApiRelayApiInitCore(dataDir: dataDir);

String storeHighlight({
  required String text,
  required String summary,
  required List<String> tags,
  String? sourceUrl,
  String? sourceTitle,
  String? sourceAuthor,
}) => RustLib.instance.api.crateApiRelayApiStoreHighlight(
  text: text,
  summary: summary,
  tags: tags,
  sourceUrl: sourceUrl,
  sourceTitle: sourceTitle,
  sourceAuthor: sourceAuthor,
);

EnrichResult enrichAndStore({required String text}) =>
    RustLib.instance.api.crateApiRelayApiEnrichAndStore(text: text);

List<SearchResultResponse> searchHighlights({
  required String query,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiRelayApiSearchHighlights(
  query: query,
  limit: limit,
);

List<ListedHighlightResponse> listStoredHighlights({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiRelayApiListStoredHighlights(
  limit: limit,
  offset: offset,
);

void deleteHighlight({required String id}) =>
    RustLib.instance.api.crateApiRelayApiDeleteHighlight(id: id);

void logEvent({required String eventType, String? streamId, String? channel}) =>
    RustLib.instance.api.crateApiRelayApiLogEvent(
      eventType: eventType,
      streamId: streamId,
      channel: channel,
    );

void registerDeviceToken({required String token, required String platform}) =>
    RustLib.instance.api.crateApiRelayApiRegisterDeviceToken(
      token: token,
      platform: platform,
    );

String createStream({required String title, required String description}) =>
    RustLib.instance.api.crateApiRelayApiCreateStream(
      title: title,
      description: description,
    );

void addHighlightToStream({
  required String streamId,
  required String highlightId,
}) => RustLib.instance.api.crateApiRelayApiAddHighlightToStream(
  streamId: streamId,
  highlightId: highlightId,
);

StreamInfoResponse getStream({required String streamId}) =>
    RustLib.instance.api.crateApiRelayApiGetStream(streamId: streamId);

List<StreamInfoResponse> listMyStreams() =>
    RustLib.instance.api.crateApiRelayApiListMyStreams();

void subscribeToStream({required String streamId}) =>
    RustLib.instance.api.crateApiRelayApiSubscribeToStream(streamId: streamId);

List<FeedHighlightResponse> getSubscriberFeed({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiRelayApiGetSubscriberFeed(
  limit: limit,
  offset: offset,
);

AuthResultResponse createAccount({
  required String email,
  required String password,
}) => RustLib.instance.api.crateApiRelayApiCreateAccount(
  email: email,
  password: password,
);

AuthResultResponse logIn({required String email, required String password}) =>
    RustLib.instance.api.crateApiRelayApiLogIn(
      email: email,
      password: password,
    );

void logOut() => RustLib.instance.api.crateApiRelayApiLogOut();

AuthStatusResponse getAuthStatus() =>
    RustLib.instance.api.crateApiRelayApiGetAuthStatus();

SyncReportResponse syncNow() => RustLib.instance.api.crateApiRelayApiSyncNow();

SyncStatusResponse getSyncStatus() =>
    RustLib.instance.api.crateApiRelayApiGetSyncStatus();

List<ConflictResponse> getConflicts() =>
    RustLib.instance.api.crateApiRelayApiGetConflicts();

void resolveConflict({required String id, required String resolution}) =>
    RustLib.instance.api.crateApiRelayApiResolveConflict(
      id: id,
      resolution: resolution,
    );

String exportLocalData() =>
    RustLib.instance.api.crateApiRelayApiExportLocalData();

void clearLocalData() => RustLib.instance.api.crateApiRelayApiClearLocalData();

bool getAutoCaptureEnabled() =>
    RustLib.instance.api.crateApiRelayApiGetAutoCaptureEnabled();

void setAutoCaptureEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiRelayApiSetAutoCaptureEnabled(enabled: enabled);

ModelStatusResponse getModelStatus() =>
    RustLib.instance.api.crateApiRelayApiGetModelStatus();

SourceMetaResponse extractSourceMetadata({required String text}) =>
    RustLib.instance.api.crateApiRelayApiExtractSourceMetadata(text: text);

class EnrichResult {
  final String id;
  final String summary;
  final List<String> tags;
  final String? suggestionHighlightId;
  final String? suggestionBridgingSentence;
  final String? sourceUrl;
  final String? sourceTitle;
  final String? sourceAuthor;

  const EnrichResult({
    required this.id,
    required this.summary,
    required this.tags,
    this.suggestionHighlightId,
    this.suggestionBridgingSentence,
    this.sourceUrl,
    this.sourceTitle,
    this.sourceAuthor,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      summary.hashCode ^
      tags.hashCode ^
      suggestionHighlightId.hashCode ^
      suggestionBridgingSentence.hashCode ^
      sourceUrl.hashCode ^
      sourceTitle.hashCode ^
      sourceAuthor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnrichResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          summary == other.summary &&
          tags == other.tags &&
          suggestionHighlightId == other.suggestionHighlightId &&
          suggestionBridgingSentence == other.suggestionBridgingSentence &&
          sourceUrl == other.sourceUrl &&
          sourceTitle == other.sourceTitle &&
          sourceAuthor == other.sourceAuthor;
}
