// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AuthResultResponse {
  final String token;
  final String userId;

  const AuthResultResponse({required this.token, required this.userId});

  @override
  int get hashCode => token.hashCode ^ userId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthResultResponse &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          userId == other.userId;
}

class AuthStatusResponse {
  final bool loggedIn;
  final String? email;

  const AuthStatusResponse({required this.loggedIn, this.email});

  @override
  int get hashCode => loggedIn.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStatusResponse &&
          runtimeType == other.runtimeType &&
          loggedIn == other.loggedIn &&
          email == other.email;
}

class ConflictResponse {
  final String id;
  final String recordType;
  final String recordId;

  const ConflictResponse({
    required this.id,
    required this.recordType,
    required this.recordId,
  });

  @override
  int get hashCode => id.hashCode ^ recordType.hashCode ^ recordId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictResponse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          recordType == other.recordType &&
          recordId == other.recordId;
}

class FeedHighlightResponse {
  final String id;
  final String text;
  final String summary;
  final List<String> tags;
  final String streamTitle;

  const FeedHighlightResponse({
    required this.id,
    required this.text,
    required this.summary,
    required this.tags,
    required this.streamTitle,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      summary.hashCode ^
      tags.hashCode ^
      streamTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeedHighlightResponse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          summary == other.summary &&
          tags == other.tags &&
          streamTitle == other.streamTitle;
}

class ListedHighlightResponse {
  final String id;
  final String text;
  final String summary;
  final List<String> tags;
  final String createdAt;
  final String? sourceUrl;
  final String? sourceTitle;
  final String? sourceAuthor;
  final String? connectionSuggestion;

  const ListedHighlightResponse({
    required this.id,
    required this.text,
    required this.summary,
    required this.tags,
    required this.createdAt,
    this.sourceUrl,
    this.sourceTitle,
    this.sourceAuthor,
    this.connectionSuggestion,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      text.hashCode ^
      summary.hashCode ^
      tags.hashCode ^
      createdAt.hashCode ^
      sourceUrl.hashCode ^
      sourceTitle.hashCode ^
      sourceAuthor.hashCode ^
      connectionSuggestion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListedHighlightResponse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          text == other.text &&
          summary == other.summary &&
          tags == other.tags &&
          createdAt == other.createdAt &&
          sourceUrl == other.sourceUrl &&
          sourceTitle == other.sourceTitle &&
          sourceAuthor == other.sourceAuthor &&
          connectionSuggestion == other.connectionSuggestion;
}

class ModelStatusResponse {
  final bool loaded;
  final String modelName;
  final String backend;

  const ModelStatusResponse({
    required this.loaded,
    required this.modelName,
    required this.backend,
  });

  @override
  int get hashCode => loaded.hashCode ^ modelName.hashCode ^ backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelStatusResponse &&
          runtimeType == other.runtimeType &&
          loaded == other.loaded &&
          modelName == other.modelName &&
          backend == other.backend;
}

class SearchResultResponse {
  final String id;
  final String summary;
  final List<String> tags;
  final String text;
  final double score;

  const SearchResultResponse({
    required this.id,
    required this.summary,
    required this.tags,
    required this.text,
    required this.score,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      summary.hashCode ^
      tags.hashCode ^
      text.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResultResponse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          summary == other.summary &&
          tags == other.tags &&
          text == other.text &&
          score == other.score;
}

class SourceMetaResponse {
  final String? sourceUrl;
  final String? sourceTitle;
  final String? sourceAuthor;

  const SourceMetaResponse({
    this.sourceUrl,
    this.sourceTitle,
    this.sourceAuthor,
  });

  @override
  int get hashCode =>
      sourceUrl.hashCode ^ sourceTitle.hashCode ^ sourceAuthor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceMetaResponse &&
          runtimeType == other.runtimeType &&
          sourceUrl == other.sourceUrl &&
          sourceTitle == other.sourceTitle &&
          sourceAuthor == other.sourceAuthor;
}

class StreamInfoResponse {
  final String id;
  final String userId;
  final String title;
  final String description;

  const StreamInfoResponse({
    required this.id,
    required this.userId,
    required this.title,
    required this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^ userId.hashCode ^ title.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamInfoResponse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          title == other.title &&
          description == other.description;
}

class SyncReportResponse {
  final PlatformInt64 pushed;
  final PlatformInt64 pulled;
  final PlatformInt64 conflicts;

  const SyncReportResponse({
    required this.pushed,
    required this.pulled,
    required this.conflicts,
  });

  @override
  int get hashCode => pushed.hashCode ^ pulled.hashCode ^ conflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncReportResponse &&
          runtimeType == other.runtimeType &&
          pushed == other.pushed &&
          pulled == other.pulled &&
          conflicts == other.conflicts;
}

class SyncStatusResponse {
  final String status;
  final PlatformInt64 pendingCount;

  const SyncStatusResponse({required this.status, required this.pendingCount});

  @override
  int get hashCode => status.hashCode ^ pendingCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          pendingCount == other.pendingCount;
}
